version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3005:3005'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    command: npm start
