name: CI/CD Pipeline for Forex_AI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start with Docker Compose
        run: docker compose up  --build -d

      - name: Check container logs
        run: docker compose logs

      - name: Stop Container
        if: always()
        run: docker compose down

      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}

      - name: Tag and Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag forex_ai_analyzer-app ghcr.io/${{ github.repository_owner }}/forex_ai_analyzer:latest
          docker push ghcr.io/${{ github.repository_owner }}/forex_ai_analyzer:latest
